export const GET_ALL_DEAL_REQUEST = "DEAL/GET_ALL_DEAL_REQUEST";
export const GET_ALL_DEAL_SUCCESS = "DEAL/GET_ALL_DEAL_SUCCESS";
export const GET_ALL_DEAL_FAILURE = "DEAL/GET_ALL_DEAL_FAILURE";

export const FETCH_DEAL_REQUEST = "DEAL/FETCH_DEAL_REQUEST";
export const FETCH_DEAL_SUCCESS = "DEAL/FETCH_DEAL_SUCCESS";
export const FETCH_DEAL_FAILURE = "DEAL/FETCH_DEAL_FAILURE";

export const FETCH_DEAL_CATEGORY_REQUEST = "DEAL/FETCH_DEAL_CATEGORY_REQUEST";
export const FETCH_DEAL_CATEGORY_SUCCESS = "DEAL/FETCH_DEAL_CATEGORY_SUCCESS";
export const FETCH_DEAL_CATEGORY_FAILURE = "DEAL/FETCH_DEAL_CATEGORY_FAILURE";

export const TAKE_DEAL_REQUEST = "DEAL/TAKE_DEAL_REQUEST";
export const TAKE_DEAL_SUCCESS = "DEAL/TAKE_DEAL_SUCCESS";
export const TAKE_DEAL_FAILURE = "DEAL/TAKE_DEAL_FAILURE";

export const CANCEL_DEAL_REQUEST = "DEAL/CANCEL_DEAL_REQUEST";
export const CANCEL_DEAL_SUCCESS = "DEAL/CANCEL_DEAL_SUCCESS";
export const CANCEL_DEAL_FAILURE = "DEAL/CANCEL_DEAL_FAILURE";