export const SIGNUP_REQUEST = "AUTH/SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "AUTH/SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "AUTH/SIGNUP_FAILURE";

export const LOGIN_REQUEST = "AUTH/LOGIN_REQUEST";
export const LOGIN_SUCCESS = "AUTH/LOGIN_SUCCESS";
export const LOGIN_FAILURE = "AUTH/LOGIN_FAILURE";

export const FORGOT_REQUEST = "AUTH/FORGOT_REQUEST";
export const FORGOT_SUCCESS = "AUTH/FORGOT_SUCCESS";
export const FORGOT_FAILURE = "AUTH/FORGOT_FAILURE";

export const GET_MY_INFO_REQUEST = "AUTH/GET_MY_INFO_REQUEST";
export const GET_MY_INFO_SUCCESS = "AUTH/GET_MY_INFO_SUCCESS";
export const GET_MY_INFO_FAILURE = "AUTH/GET_MY_INFO_FAILURE";

export const LOGOUT_REQUEST = "AUTH/LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "AUTH/LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "AUTH/LOGOUT_FAILURE";


export const PHONE_VERIFY_REQUEST = "AUTH/PHONE_VERIFY_REQUEST";
export const PHONE_VERIFY_SUCCESS = "AUTH/PHONE_VERIFY_SUCCESS";
export const PHONE_VERIFY_FAILURE = "AUTH/PHONE_VERIFY_FAILURE";

export const LOGOUT_UNAUTHENTICATED = "AUTH/LOGOUT_UNAUTHENTICATED";
