export const GET_ALL_BUSINESS_REQUEST = "BUSINESS/GET_ALL_BUSINESS_REQUEST";
export const GET_ALL_BUSINESS_SUCCESS = "BUSINESS/GET_ALL_BUSINESS_SUCCESS";
export const GET_ALL_BUSINESS_FAILURE = "BUSINESS/GET_ALL_BUSINESS_FAILURE";

export const FETCH_BUSINESS_REQUEST = "BUSINESS/FETCH_BUSINESS_REQUEST";
export const FETCH_BUSINESS_SUCCESS = "BUSINESS/FETCH_BUSINESS_SUCCESS";
export const FETCH_BUSINESS_FAILURE = "BUSINESS/FETCH_BUSINESS_FAILURE";
